apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: token
  annotations:
    kubernetes.io/service-account.name: build-robot
type: kubernetes.io/service-account-token

---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-pod
  namespace: default
  labels:
    app: token-pod
spec:
  selector:
    matchLabels:
      app: token-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: token-pod
    spec:
      containers:
      - name: token-pod
        image: ubuntu
        command:
          - sleep
          - "3600"
      serviceAccountName: build-robot
---

